# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ClickSignServer CI/CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20'

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 9

      # - name: Install dependencies
      #   run: pnpm install

      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: clicksoftkr/click-sign-server:latest, clicksoftkr/click-sign-server:${{ github.run_number }}

      - name: Checkout k8s-update repository
        uses: actions/checkout@v3
        with:
          repository: clicksoft-ko/ai-server-k8s
          token: ${{ secrets.K8S_UPDATE_TOKEN }}
          path: ai-server-k8s
          ref: main

      - name: Install yq (fast)
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml (yq)
        run: |
          yq -i '.server.image.version = "${{ github.run_number }}"' ai-server-k8s/projects/click-sign/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "ci-cd"
          git config --global user.email "actions@github.com"
          cd ai-server-k8s
          git add projects/click-sign/values.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push
